GET http://localhost:8080/api/v1/dummy/headers
User-Location: Mumbai
#User-Agent: Rutam

###
GET http://localhost:8080/api/v1/dummy/user/map/123/post/456

###
#GET http://localhost:8080/api/v1/dummy/user/102920/post/4785
GET http://localhost:8080/api/v1/dummy/user/102920
Accept: application/json

###
GET http://localhost:8080/api/v1/dummy/search?name=Rutam
Accept: application/json

###

GET http://localhost:8080/api/v1/dummy/multiple-search?firstName=Rutam&lastName=Kulkarni
Accept: application/json


###
POST http://localhost:8080/api/v1/dummy/create-user
Content-Type: application/json

{
  "name" : "Rutam Kulkarni",
  "email" : "rutam2003@gmail.com",
  "mobileNumber" : "8928252679"
}

###
POST http://localhost:8080/api/v1/dummy/create-user